[Fix] /unlockview layout
DeveloperAcademy-POSTECH/MacC-Team-SecretAgent pull request #104
Opened 2022-12-03 03:18 UTC by KimDaeSeong8721

## ⁴/₄ 관련 이슈

- close #103 
## ⁴/₄ 작업내용

<img width="1478" alt="image" src="https://user-images.githubusercontent.com/69894461/205419803-21968280-7601-4a3e-9dac-5640fe4acf84.png">

## ⁴/₄ PR 포인트

 - 아이폰 미니 높이 기준으로 높이보다 작으면 비율값을 더 크게 조정하였습니다. 더 나은 방법이 있으시면 편히 말씀해주세요!

2022-12-03 03:24 UTC, cozytk approved these changes
확인했습니다!

2022-12-03 05:39 UTC, JIW00NG requested changes
SE 고려하는 것이 쉽지만은 않았을 텐데 신경쓰면서 하신 모습이 보이네요👍

2022-12-03 05:39 UTC, JIW00NG commented on SecretAgent/SecretAgent/Screen/Siren/UnlockViewController.swift
> +    static let resultViewTopOffset =  UIScreen.main.bounds.height >= 780 ? UIScreen.main.bounds.height / 8.98 : UIScreen.main.bounds.height / 15.00
p1
현재 코드는 화면의 높이가 780 이상인 경우와 아닌 경우로 나누고 계시네요?!
이는 SE의 크기가 작아서 이러한부분을 고려한 수치로 결정하였다고 생각합니다.
밀러가 하신 방법도 가능하지만 제가 제안하고 싶은 방법은 화면 비율에 따라서 뷰의 크기를 다르게 설정하는 것 입니다.

제가 확인해본 결과 노치가 있는 화면과 노치가 없는 화면 비율은 각각 약 2.16(노치 O), 약 1.77이였습니다.
그렇다면 화면의 가로 세로 비율이 2를 넘어가는 화면과 2를 넘어가지 않는 화면의 뷰 크기를 다르게 지정한다면 해결될 것이라고 생각합니다.
밀러의 코드를 화면 비율을 고려한 것으로 수정한다면 다음과 같습니다.

```swift
static let resultViewTopOffset =  UIScreen.main.bounds.height / UIScreen.main.bounds.width > 2 ? UIScreen.main.bounds.height / 8.98 : UIScreen.main.bounds.height / 15.00
```

2022-12-03 05:39 UTC, JIW00NG commented on SecretAgent/SecretAgent/Screen/Siren/UnlockViewController.swift
> +            make.bottom.equalTo(buttonHStackView.snp.top).offset(-Size.buttonVStackViewVerticalOffset) // inset(70)하면 안되는데 이유가..
확인해보니까 equalTo() 에 들어가는 View를 기준으로 top의 inset은 offset 양수, bottom의 inset은 offset 음수로 적용되고 있습니다. 
예를 들면 `make.bottom.equalTo(view.snp.top).inset(70)`은 `make.bottom.equalTo(view.snp.top).offset(70)`과 같고
`make.bottom.equalTo(view.snp.bottom).inset(70)`은 `make.bottom.equalTo(view.snp.bottom).offset(-70)`와 같습니다. 그렇기 때문에 top을 기준으로 inset(70)을 하면 numberCollectionView가 buttonHStackView의 위에 표시되는 것이 아닌 비슷한 위치에 표시되는 것 처럼 보이고 offset(-70)로 설정해야 numberCollectionView가 buttonHStackView의 top 에서 70 떨어진 곳에 표시되는 것 입니다.

2022-12-03 07:54 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Screen/Siren/UnlockViewController.swift
> +    static let resultViewTopOffset =  UIScreen.main.bounds.height >= 780 ? UIScreen.main.bounds.height / 8.98 : UIScreen.main.bounds.height / 15.00
더 깔끔하고 좋네요 !! 반영했습니당

2022-12-03 07:59 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Screen/Siren/UnlockViewController.swift
> +            make.bottom.equalTo(buttonHStackView.snp.top).offset(-Size.buttonVStackViewVerticalOffset) // inset(70)하면 안되는데 이유가..
오 감사합니다. equalTo()에 들어가는 View기준이군요..!

2022-12-03 08:05 UTC, cozytk commented on SecretAgent/SecretAgent/Screen/Siren/UnlockViewController.swift
> +    static let resultViewTopOffset =  UIScreen.main.bounds.height >= 780 ? UIScreen.main.bounds.height / 8.98 : UIScreen.main.bounds.height / 15.00
ㅋㅋㅋ신선한 방법이네요 굿

2022-12-03 08:12 UTC, JIW00NG approved these changes
개인적인 의견이였지만 긍정적으로 생각하고 적용시켜주셔서 감사합니다!

2022-12-04 06:10 UTC, JIW00NG commented
머지해도 될 듯합니다!

2022-12-05 03:54 UTC, merged