[FEAT] 타이머 기능 구현
DeveloperAcademy-POSTECH/MacC-Team-SecretAgent pull request #11
Opened 2022-11-19 11:38 UTC by KimDaeSeong8721

## ⁴/₄ 관련 이슈

- close #4 
## ⁴/₄ 작업내용

- 빠른 UI구현을 위해서 스토리보드에서 작업을 해보았습니다.
- 프로그래스바를 구현하였습니다.
- 타이머 기능을 구현하였고, 앱이 백그라운드 상태여서 포그라운드 상태로 돌아올 때도 타이머 기능이 작동되도록 구현하였습니다.
<img width="379" alt="image" src="https://user-images.githubusercontent.com/69894461/202848707-780682ef-6883-405e-a28d-4894da96f2b0.png">

## ⁴/₄ PR 포인트

- 카운트 타이머가 작동하는 중에 앱이 완전히 종료되고 다시 들어왔을 때도 타이머 기능이 재개되도록 해야할지 고민입니다.

## ⁴/₄ 다음으로 진행될 작업
 - [ ] 앱 완전히 종료후 재접속시 타이머 기능 재개

2022-11-19 12:19 UTC, JIW00NG requested changes
저는 아직 제대로된 코드도 작성하지 못하는 상황에서 바로바로 타이머를 구현하셨네요.
역시... 밀러👍
밀러는 개발을 잘해...
쫓아가겠습니다.🏃🏼‍♀️

2022-11-19 12:19 UTC, JIW00NG commented on SecretAgent/SecretAgent/Screen/Siren/View/Component/ProgressBar.swift
> +        foregroundProgressLayer.path = UIBezierPath(
UIBezierPath 로 다양한 모양의 view를 그리는 것이군요...
SwiftUI에서 저런 모양을 그리기 위해 Circle()을 사용했는데 UIKit은 이런 방식으로 하는 것 잘 알아갑니다 ㅎㅎ👍

2022-11-19 12:19 UTC, JIW00NG commented on SecretAgent/SecretAgent/Screen/Siren/View/Component/ProgressBar.swift
> +        animation.toValue = Double(1.0)
p3
0.0은 자동으로 Double type으로 초기화 됩니다.
swiftformat을 따른 것이라면 아래의 코드 또한 동일하게 Float(1.0) 또는 Double(1.0)으로 되어야 한다고 생각합니다.
`foregroundProgressLayer.speed = 1.0`
다른 이유에서 Double 로 지정하셨을까요? 궁금해요

2022-11-19 12:19 UTC, JIW00NG commented on SecretAgent/SecretAgent/Screen/Siren/View/Component/ProgressBar.swift
> +        fillColor = nil
p5
backgoroundColor를 투명으로 설정했는데 fillColor를 따로 nil로 설정해야 투명색이 적용되는 것인가요?
궁금궁금해요

2022-11-19 13:05 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Screen/Siren/CountDownTimer.swift
> +        timer = Timer.scheduledTimer(timeInterval: 0.01, target: self, selector: #selector(updateTimer), userInfo: nil, repeats: true) // 왜 0.01초로 했을까?
음,, 0.0 보다 0.01이 더 크기때문에 0.01로 설정되지 않을까요? 0.0보다 작은 경우는 음수라서 음수인 경우에 0.0001로 설정되는 것으로 이해했습니다..!

2022-11-19 13:09 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Screen/Siren/CountDownTimer.swift
> +    }
타이머 객체는 외부에서 함부로 바꾸면 안되기 때문에 private으로 선언을 했고 이 타이머 객체를 멈추기 위해 timer.invalidate()를 함수로 만들었습니다. 그래서 외부에서는 timer에 접근할 수 없고 timer가 멈추는 함수기능코드만 접근하도록 해놓았는데 혹시 이 부분이 문제가 될까요?

2022-11-19 13:11 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Screen/Siren/CountDownTimer.swift
> +    }
이 부분은 삭제하고 runTimer의 private을 제거해서 직접 접근하도록 하겠습니다!

2022-11-19 13:13 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Screen/Siren/SirenViewController.swift
> +    @IBOutlet var startButton: UIButton!
네! 그렇습니다

2022-11-19 13:13 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Screen/Siren/View/Component/ProgressBar.swift
> +    @available(*, unavailable)
아닙니다. swiftformat이 ㅎㅎ...

2022-11-19 13:13 UTC, JIW00NG commented on SecretAgent/SecretAgent/Screen/Siren/CountDownTimer.swift
> +        timer = Timer.scheduledTimer(timeInterval: 0.01, target: self, selector: #selector(updateTimer), userInfo: nil, repeats: true) // 왜 0.01초로 했을까?
0.01초 뒤에 타이머를 설정하는 이유는 무엇인가요?
타이머 시작하면 바로 타이머가 돌아가야한다고 생각해서 최소한의 딜레이만 있어야한다고 생각하는데 0.01초로 설정하신 이유가 있으신가요?

2022-11-19 13:14 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Screen/Siren/View/Component/ProgressBar.swift
> +        foregroundProgressLayer.path = UIBezierPath(
저도 이부분에 대한 이해가 깊지 않아 수일 내로 wiki에 UIBezierPath, CALayer, CAShapeLayer와 관련된 글을 작성해보겠습니다.

2022-11-19 13:16 UTC, JIW00NG commented on SecretAgent/SecretAgent/Screen/Siren/CountDownTimer.swift
> +    }
문제가 전혀 되지 않습니다. ㅎㅎ
보통 함수가 호출되면 함수는 Stack에 쌓이게 되고 함수 호출이 늘어나게 된다면 불필요하게 Stack 공간을 사용한다고 알고 있습니다. 그렇기 때문에 만약 함수 내부 코드가 다른 함수를 호출하는 것 뿐이라면 그냥 직접 접근하는 것이 효율적이라고 알고 있어서 저런 리뷰를 남겼습니다.

2022-11-19 13:17 UTC, JIW00NG commented on SecretAgent/SecretAgent/Screen/Siren/View/Component/ProgressBar.swift
> +        foregroundProgressLayer.path = UIBezierPath(
기대하겠습니다 밀러
(밀러는 설명을 잘해)

2022-11-19 13:19 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Screen/Siren/View/Component/ProgressBar.swift
> +        animation.toValue = Double(1.0)
0.0 // 1.0 으로 수정했습니다.🫡

2022-11-19 13:25 UTC, KimDaeSeong8721 commented
> 저는 아직 제대로된 코드도 작성하지 못하는 상황에서 바로바로 타이머를 구현하셨네요. 역시... 밀러👍 밀러는 개발을 잘해... 쫓아가겠습니다.🏃🏼‍♀️

우기 겸손하시네요.. 🙄

2022-11-19 13:35 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Screen/Siren/CountDownTimer.swift
> +        timer = Timer.scheduledTimer(timeInterval: 0.01, target: self, selector: #selector(updateTimer), userInfo: nil, repeats: true) // 왜 0.01초로 했을까?
원래는 1초간격으로 하려고 했습니다. 1초마다 업데이트함수가 호출되도록..!! 그러나 마지막에 끝나는 타이밍이 조금 느려지는 이슈가 있었습니다. 그래서 타이밍을 좀 더 빠르게 하기 위해  대략 0.01초간격으로 바꿨습니다. 0.0001초로도 할 수 있지만 0.0001초마다 updateTimer함수를 계속 호출해야하는데 그럼 1초가 지나면 updateTimer함수가 1만번이 실행되어야 합니다.  너무 딜레이를 적게 주면 함수호출을 너무 많이 해서 0.01초로 설정했습니다.. 😅

2022-11-19 16:11 UTC, Minkyeong-Ko approved these changes
빠른 구현 너무나 멋있습니다 밀러 수고하셨습니다

2022-11-19 16:11 UTC, Minkyeong-Ko commented on SecretAgent/SecretAgent/Screen/Siren/View/Component/ProgressBar.swift
> +                                           y: frame.height / 2)
p5.
init이 실행된 후에 frame이 결정되어서 lazy var로 만들어 진 건가요? (단순 저의 이해를 위한 질문이에요..😅)

2022-11-19 16:11 UTC, Minkyeong-Ko commented on SecretAgent/SecretAgent/Screen/Siren/View/Component/ProgressBar.swift
> +private enum Size {
p3.
ProgressBarSize 등으로 이름을 바꾸는 건 어떨까요?

2022-11-19 16:11 UTC, Minkyeong-Ko commented on SecretAgent/SecretAgent/Global/Support/SceneDelegate.swift
> +        NotificationCenter.default.post(name: NSNotification.Name("sceneWillEnterForeground"), object: nil, userInfo: ["time": interval])
Notification 관련 코드를 완벽히 이해하지 못해서..ㅠㅠ 질문 양해 부탁드립니다..
백그라운드 상태에서 타이머가 종료되면 어떤 일이 벌어지나요? 
그리고 시간이 끝난 후에 foreground로 돌아오면 어떻게 처리되는지도 궁금합니다..🤓

2022-11-20 03:44 UTC, JIW00NG approved these changes
리뷰 반영 감사합니다.

2022-11-20 05:04 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent.xcodeproj/project.pbxproj
> +			shellScript = "export PATH=\"$PATH:/opt/homebrew/bin\"\nif which swiftformat > /dev/null; then\n  swiftformat  . --swiftversion 5.7\nelse\n  echo \"error: SwiftFormat not installed, download from
제가 --lint 추가하려다가 안했는데 생겼나보네요.. lint다시 추가했습니다

2022-11-20 05:06 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Screen/Siren/CountDownTimer.swift
> +        timer = Timer.scheduledTimer(timeInterval: 0.01, target: self, selector: #selector(updateTimer), userInfo: nil, repeats: true) // 왜 0.01초로 했을까?
아닙니다!! 우기가 질문을 해서 저도 scheduledTimer에 대해 더 깊게 탐구해보는 시간을 가질 수 있었습니다. 감사합니다 👏

2022-11-20 05:09 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Screen/Siren/CountDownTimer.swift
> +        let secondsToSeconds = seconds
좀 더 명시적으로 보여주기 위해 지역변수를 만들었는데
```swift
        let totalSeconds = minutes * 60 + seconds

``` 로 변경하도록 하겠습니다!

2022-11-20 05:13 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Screen/Siren/SirenViewController.swift
> +            make.centerY.equalToSuperview()
<img width="783" alt="image" src="https://user-images.githubusercontent.com/69894461/202886746-08fe4251-8e74-4cdb-a2c0-51f52682c85e.png">
감사합니다. 다니. 덕분에 코드 두 줄에서 한 줄로 줄일 수 있군요. ㅎㅎ. 반영하겠습니다

2022-11-20 05:17 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Screen/Siren/View/Component/ProgressBar.swift
> +                                           y: frame.height / 2)
맞아요. ProgressBar의 인스턴스가 생성되기 전에 프로퍼티들이 메모리에 로드되는데 lazy를 선언해줌으로써 그 프로퍼티의 초기화를 사용할때 하도록 늦출수 있습니다. 그렇게 한 이유는 frame은 인스턴스가 생성되고 나서 접근할 수 있기 때문입니다!

2022-11-20 05:18 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Screen/Siren/View/Component/ProgressBar.swift
> +private enum Size {
ProgressBar에서만 사용되는 enum이라 Size로 선언했는데 보다 명시적으로 ProgressBarSize로 변경하도록 하겠습니다!

2022-11-20 05:22 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Global/Support/SceneDelegate.swift
> +        NotificationCenter.default.post(name: NSNotification.Name("sceneWillEnterForeground"), object: nil, userInfo: ["time": interval])
사실 백그라운드 상태에서는 타이머가 작동을 하지 않습니다.
제가 작성한 코드는 백그라운드 상태에서 타이머가 작동을 한 것처럼 보이게 하는 코드입니다.
백그라운드로 갈 때 그 순간의 Date()를 UserDefaults에 저장을 하고 forground로 들어왔을 때 UserDefaults에 저장한 Date()와 현재의 Date()의 차이를 현재 남아있는 시간인 duration에서 차감했습니다. 그래서 백그라운드 상태에서 저희가 설정한 카운트타이머 시간을 넘어서면 foreground로 돌아오자마자 duration은 음수가 되고 타이머는 멈춥니다.

2022-11-20 06:15 UTC, merged

2022-11-20 06:18 UTC, Minkyeong-Ko commented on SecretAgent/SecretAgent/Screen/Siren/View/Component/ProgressBar.swift
> +private enum Size {
아.. private이라 이름이 Size여도 크게 문제가 없군요..!! 그렇다면 그냥 Size가 나은 것 같네요 밀러 죄송합니다😅

2022-11-20 06:20 UTC, Minkyeong-Ko commented on SecretAgent/SecretAgent/Global/Support/SceneDelegate.swift
> +        NotificationCenter.default.post(name: NSNotification.Name("sceneWillEnterForeground"), object: nil, userInfo: ["time": interval])
그러면 사용자가 타이머를 켜 놓고 잠금했을 때 타이머가 끝났다는 것을 어떻게 알 수 있나요..?!

2022-11-20 07:41 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Global/Support/SceneDelegate.swift
> +        NotificationCenter.default.post(name: NSNotification.Name("sceneWillEnterForeground"), object: nil, userInfo: ["time": interval])
좋은 피드백 감사합니다.  백그라운드에서 타이머가 끝나는 순간을 인지해서 알림을 띄워주는 것을 고려를 안하고 있었습니다. 이 부분을 알기 위해서는 비동기 프로그래밍을 이용해야 싶을 듯합니다. 관련정보 찾아보고 코드수정하고 PR올리도록 하겠습니다

2022-11-20 08:04 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Global/Support/SceneDelegate.swift
> +        NotificationCenter.default.post(name: NSNotification.Name("sceneWillEnterForeground"), object: nil, userInfo: ["time": interval])
@Minkyeong-Ko  다시 고민을 해보니 DispatchSourceTimer를 이용할 필요없이 현재 코드에서 background로 돌입할때 타이머시간과 남은시간의 차이를 UserNotification의 예약시간으로 걸어놓으면 될거 같습니다!!

2022-11-20 08:06 UTC, cozytk reviewed
밀러의 코드 리뷰 너무 즐겁네요. 같이 고민했으면 하는 부분들 리뷰 남겨놓았습니다. 몇가지 추가적인 리뷰포인트들 아래에 남겨놓아요.
1. 

![STOP눌러야됨](https://user-images.githubusercontent.com/59143479/202891928-9746688c-7eb0-46e1-92f8-a19690a03049.gif)

위의 GIF 처럼 타이머가 끝나고 다음에 `start` 를 누를때는 애니메이션이 채워지지 않는 버그가 있어요! `stop` 을 꼭 눌러야 초기화가 되더라구요.

2. `resume` 을 구현하신 이유가 있을까요? 저희 비즈니스 로직상 `resume` 하는 경우가 없다고 생각했는데 그냥 타이머를 구현하면서 하신건지 궁금해요!

2022-11-20 08:29 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Screen/Siren/CountDownTimer.swift
> +        let minutes = Int(time) / 60 % 60
시간 단위를 다루지 않아서 고민하다가 일단 넣어놨는데 빼겠습니다!

2022-11-20 08:29 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Screen/Siren/CountDownTimer.swift
> +    @objc func pause() {
아 섬세한 피드백  감사합니다!

2022-11-20 08:35 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Global/Support/SceneDelegate.swift
> +        let interval = Int(Date().timeIntervalSince(start))
음 생각지도 못한 디테일 부분 피드백주셔서 감사합니다. duration도 0.01씩 줄어들기 때문에 코지 말씀처럼 소숫점자리를 살려두는게 정확성이 더 좋다고 판단됩니다. 반영하겠습니다!

2022-11-20 08:53 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Screen/Siren/CountDownTimer.swift
> +    private var seconds = 0.0
공감합니다 :) private let totalSeconds 로 선언하고 countTimer 생성시 생성자의 파라미터로 받아서 초기화하도록 하겠습니다!

2022-11-20 08:56 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Screen/Siren/View/Component/ProgressBar.swift
> +    private func loadBackgroundProgressBar() {
공감해요. 이런 디테일 중요합니다.!

2022-11-20 08:56 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Screen/Siren/View/Component/ProgressBar.swift
> +            radius: frame.width / 2 - 30.0,
저희 UI디자인이 나오지 않아서 대략적으로 넣어준 수치입니다. 변경예정입니다!

2022-11-20 13:14 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Screen/Siren/View/Component/ProgressBar.swift
> +    func setProgressBar(minutes: Int, seconds: Int) {
새로운 PR에 반영하겠습니다!!

2022-11-20 13:15 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Screen/Siren/View/Component/ProgressBar.swift
> +        loadForegroundProgressBar()
스토리보드 상에서 progressBar 파라미터 있는 생성자로 인스턴스 만드는 방법이,, 떠오르지 않아 코드베이스로 다시 구성했습니다.

2022-11-20 13:26 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Screen/Siren/CountDownTimer.swift
> +        timer = Timer.scheduledTimer(timeInterval: 0.01, target: self, selector: #selector(updateTimer), userInfo: nil, repeats: true) // 왜 0.01초로 했을까?
selector를 사용하는 방식은 objective-c와 swift를 공존하는 과정에서 사용되어 왔기 때문에 최신코드인 Sendable 방식(ios 10이상)을 활용하는 게 더 나아보입니다. 내부적으로 어떤 이득이 있는지는 좀 더 자료를 찾아보겠습니다!

2022-11-20 13:31 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Screen/Siren/CountDownTimer.swift
> +        timer = Timer.scheduledTimer(timeInterval: 0.01, target: self, selector: #selector(updateTimer), userInfo: nil, repeats: true) // 왜 0.01초로 했을까?
그리고 궁금한 점이 있는데 guard let self else { return }을 사용한 이유가 있을까요? 🙃

2022-11-20 13:34 UTC, cozytk commented on SecretAgent/SecretAgent/Screen/Siren/View/Component/ProgressBar.swift
> +        loadForegroundProgressBar()
앗.. 귀찮게했군여

2022-11-20 13:39 UTC, cozytk commented on SecretAgent/SecretAgent/Screen/Siren/CountDownTimer.swift
> +        timer = Timer.scheduledTimer(timeInterval: 0.01, target: self, selector: #selector(updateTimer), userInfo: nil, repeats: true) // 왜 0.01초로 했을까?
@KimDaeSeong8721 self 옵셔널로 써주기 귀찮아서 사용했습니다..

2022-11-20 13:46 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Screen/Siren/CountDownTimer.swift
> +        timer = Timer.scheduledTimer(timeInterval: 0.01, target: self, selector: #selector(updateTimer), userInfo: nil, repeats: true) // 왜 0.01초로 했을까?
guard let self else { return }를 사용하면 클로저안의 모든 코드들이 실행이 되기전까지는 강한 참조가 되는 걸로 알고 있어서 궁금해서 물어보았습니다 :)  아 그리고 코지가 제시한 코드로 구현해보았는데 또다른 버그가 발생했네요 ㅜㅜ. 스타트를 여러번하면 10초타이머가 점점 빨라져서 10초도 안되서 종료가 되네요 ,, 흠

2022-11-20 13:48 UTC, KimDaeSeong8721 commented
> 밀러의 코드 리뷰 너무 즐겁네요. 같이 고민했으면 하는 부분들 리뷰 남겨놓았습니다. 몇가지 추가적인 리뷰포인트들 아래에 남겨놓아요. 1.
> 
> ![STOP눌러야됨](https://user-images.githubusercontent.com/59143479/202891928-9746688c-7eb0-46e1-92f8-a19690a03049.gif) [ ![STOP눌러야됨](https://user-images.githubusercontent.com/59143479/202891928-9746688c-7eb0-46e1-92f8-a19690a03049.gif) ](https://user-images.githubusercontent.com/59143479/202891928-9746688c-7eb0-46e1-92f8-a19690a03049.gif) [ ](https://user-images.githubusercontent.com/59143479/202891928-9746688c-7eb0-46e1-92f8-a19690a03049.gif)
> 
> 위의 GIF 처럼 타이머가 끝나고 다음에 `start` 를 누를때는 애니메이션이 채워지지 않는 버그가 있어요! `stop` 을 꼭 눌러야 초기화가 되더라구요.
> 
> 2. `resume` 을 구현하신 이유가 있을까요? 저희 비즈니스 로직상 `resume` 하는 경우가 없다고 생각했는데 그냥 타이머를 구현하면서 하신건지 궁금해요!

1. 생각지도 못한 버그 찾아주셔서 감사합니다...!
2. 디자인이 안나온 것으로 알고 있어서 그냥 타이머를 구현하면서 임시로 추가했습니다

2022-11-20 14:15 UTC, cozytk commented on SecretAgent/SecretAgent/Screen/Siren/CountDownTimer.swift
> +        timer = Timer.scheduledTimer(timeInterval: 0.01, target: self, selector: #selector(updateTimer), userInfo: nil, repeats: true) // 왜 0.01초로 했을까?
@KimDaeSeong8721
제가 잘 모르지만 `self` 를 옵셔널로 사용하는 방법과 비교해서 `self` 가 있을때는 같은 조건일거고 `self` 가 `nil` 일때는 guard 에서 return 될텐데 문제가 될까요?

2022-11-20 14:16 UTC, cozytk commented on SecretAgent/SecretAgent/Screen/Siren/CountDownTimer.swift
> +        timer = Timer.scheduledTimer(timeInterval: 0.01, target: self, selector: #selector(updateTimer), userInfo: nil, repeats: true) // 왜 0.01초로 했을까?
> 코지가 제시한 코드로 구현해보았는데 또다른 버그가 발생했네요 ㅜㅜ. 스타트를 여러번하면 10초타이머가 점점 빨라져서 10초도 안되서 종료가 되네요 ,, 흠 @cozytk

오... 같은 역할을 하는 코드처럼 보이는데 차이가 있군여?!

2022-11-20 14:20 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Screen/Siren/CountDownTimer.swift
> +        timer = Timer.scheduledTimer(timeInterval: 0.01, target: self, selector: #selector(updateTimer), userInfo: nil, repeats: true) // 왜 0.01초로 했을까?
guard let self 통과하고 클로저 코드들이 실행되는 도중에 사용자에 의해 self가 해제되도록 할 때(RC가 1감소) 이때 guard let self로 인해 self의 RC가 1증가하여 self가 해제되지 못하는 타이밍 문제(?)가 있다고 알고 있습니다. 지금 상황에서는 크게 문제가 되보이지는 않습니다.. 근데 왜 버그가 생기는 걸까요? ㅜㅜ self문제는 아닌거 같습니다

2022-11-20 14:48 UTC, cozytk commented on SecretAgent/SecretAgent/Screen/Siren/CountDownTimer.swift
> +        timer = Timer.scheduledTimer(timeInterval: 0.01, target: self, selector: #selector(updateTimer), userInfo: nil, repeats: true) // 왜 0.01초로 했을까?
@KimDaeSeong8721 탐구해보고 싶네요 🤩 지식 공유 감사드립니다!