[FIX] feedback resolved third
DeveloperAcademy-POSTECH/MacC-Team-SecretAgent pull request #13
Opened 2022-11-20 13:59 UTC by KimDaeSeong8721

## ⁴/₄ 관련 이슈

- close #12 
## ⁴/₄ 작업내용

- 타이머 종료 후 다시 시작버튼을 눌렀을 때 프로그래스 바의 애니메이션이 보이지 않는 버그를 해결했습니다.
- seconds의 이름을 totalSeconds로 바꾸었고 let으로 변경하였습니다.
- CountTimer와 ProgressBar에 생성자를 이용한 의존성 주입을 하였습니다. (totalSeconds)
- 이로 인해 ProgressBar가 기존의 스토리보드로 구현된 것을 코드베이스로 변경하였습니다.
- 백그라운드로 갈때와 포그라운드로 돌아올때의 시간차이를 Int가 아니라 Double로 하여 소숫점자리를 살려두어 오차를 줄였습니다.
- animation에 필요없는 코드들을 지웠습니다.
- 하나의 파일에만 사용되는 extension에 private을 추가하였습니다.
- 프로그래스바의 애니메이션을 채워진상태에서 줄어들도록 변경했습니다.
- 
## ⁴/₄ PR 포인트

- PrgressBar에서 frame 설정을 하고나서 ViewController에서 오토레이아웃으로 위치만 center로 잡아주었는데 UI가 제대로 보여지지 않는 문제가 있었습니다. 그래서 오토레이아웃 작성하는 코드에 `progressBar.size.equalTo(300)`을 적용을 해주었더니 원하는 UI가 되었습니다. 사이즈 설정을 왜 두번을 해야되는지 아직 원인을 찾지 못했습니다.

2022-11-20 14:45 UTC, cozytk approved these changes
p5 까지 모두 반영해주시는 정성 감동입니다.. 허나 생산성에 해를 끼칠까봐 p4 이하는 정말 제안일 뿐 모두 받아들이시진 않으셔도 된다고 당부드립니다 :) 

추가적으로 PR포인트에 대해서,

> PrgressBar에서 frame 설정을 하고나서 ViewController에서 오토레이아웃으로 위치만 center로 잡아주었는데 UI가 제대로 보여지지 않는 문제가 있었습니다. 그래서 오토레이아웃 작성하는 코드에 progressBar.size.equalTo(300)을 적용을 해주었더니 원하는 UI가 되었습니다. 사이즈 설정을 왜 두번을 해야되는지 아직 원인을 찾지 못했습니다.

지금은 `equalTo(view)` 로 정상적으로 나오는데 어떤게 문제라는 말씀일까요?!

2022-11-20 14:45 UTC, cozytk commented on SecretAgent/SecretAgent/Screen/Siren/SirenViewController.swift
> +        progressBar.stop()
Q.

이 부분이 버그 해결한 전부일까용?!

2022-11-20 14:45 UTC, cozytk commented on SecretAgent/SecretAgent/Screen/Siren/View/Component/ProgressBar.swift
> +    convenience init(totalSeconds: Int) {
Q.

 혹시 `convenience init` 을 사용한 이유랑 어떻게 사용하신 건지 설명부탁드려도 될까요 👀

2022-11-20 14:45 UTC, cozytk commented on SecretAgent/SecretAgent/Screen/Siren/SirenViewController.swift
> +            make.center.equalTo(view)
p4.

`equalToSuperView()` 와 동일한게 맞나요? 혹시 위와같이 작성하신 의도가 있을까요??

2022-11-21 06:29 UTC, Minkyeong-Ko approved these changes
피드백 적용 수고하셨습니다🙇‍♀️ 
frame 관련 부분에 대해서 다른 분들 의견이 궁금한데 그 부분만 봐주시면 감사하겠습니다!

2022-11-21 06:29 UTC, Minkyeong-Ko commented on SecretAgent/SecretAgent/Screen/Siren/SirenViewController.swift
> +            make.size.equalTo(Constants.progressBarSize)
이 부분 저도 궁금해서 저도 계속 찾아봤는데, (참고한 블로그: https://velog.io/@wonhee010/Auto-Layout-vs-Frame-Based-Layout)
`ProgressBar` 에서는 `frame` 기반으로 작성했는데, 여기서는 `AutoLayout` 을 사용해서 `frame` 기반으로 한 코드가 동작하지 않는 것 같아요. 
그래서 `SnapKit` 을 사용하는 부분을 아예 주석처리 하니까 frame 설정한 대로 크기가 제대로 보이더라구요!
결론적으로 snapkit을 사용할 거면 아예 size 설정도 여기서 하는 게 맞지 않을까 하는.. 저의 뇌피셜입니다..ㅎㅎ

다른 분들은 어떻게 생각하시는 지 궁금해요 👀

2022-11-21 06:29 UTC, Minkyeong-Ko commented on SecretAgent/SecretAgent/Screen/Siren/CountDownTimer.swift
> -    func setTimer(minutes: Int, seconds: Int) {
저희는 타이머 시간이 고정돼 있으니까 파라미터를 받을 필요가 없겠네요! 점점 코드가 진화하는 게 멋있습니다👍

2022-11-21 11:35 UTC, JIW00NG requested changes
코지 왈: PR에 띄어쓰기 안지킨거 마음에 안드네요.

2022-11-21 11:35 UTC, JIW00NG commented on SecretAgent/SecretAgent/Screen/Siren/View/Component/ProgressBar.swift
> +    static let height = 300
SirenViewController에서 ProgressBar 를 300으로 설정했다면 SubView인 ProgressBar는 그냥 superView에 맞추기만 하면 300으로 설정될거에요. 그렇기 때문에 여기서 width, height을 따로 300으로 주지 않아도 된다고 생각합니다.

2022-11-21 11:35 UTC, JIW00NG commented on SecretAgent/SecretAgent/Screen/Siren/View/Component/ProgressBar.swift
> +    convenience init(totalSeconds: Int) {
저도 코지 질문 궁금해요

2022-11-21 11:38 UTC, cozytk commented
> 코지 왈: PR에 띄어쓰기 안지킨거 마음에 안드네요.

모함이에요 밀러

2022-11-22 05:30 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Screen/Siren/SirenViewController.swift
> +        progressBar.stop()
이 코드를 추가하면 생기는 문제가 타이머가 끝났을 때 프로그래스바가 초기화되어 비어있게 됩니다.
아이폰의 시계 기본앱을 참고했을 때 이미 채워진 상태에서 게이지가 줄어드는 애니메이션으로 구현한 점을 참고하여 위의 문제를 우회적으로 해결했습니다.

2022-11-22 05:44 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Screen/Siren/View/Component/ProgressBar.swift
> +    static let height = 300
어제 코지와 그 부분에 대해 여러 시도를 했는데 ProgressBar에서 frame을 고정하고 ViewController에서는 ProgressBar의 위치만 오토레이아웃으로 고정해주는 방법으로 성공했습니다. 우기의 방법대로 하면 지금의 코드에서 안되는 데, 그 이유를 생각해보았는데 ProgressBar의 init부분에서 frame 설정과 ProgressBar UI 설정 타이밍 문제가 발생으로 추정됩니다.. 혹시 더 좋은 방법이 있다면 제안 부탁드립니다 🙃

2022-11-22 05:55 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Screen/Siren/View/Component/ProgressBar.swift
> +    convenience init(totalSeconds: Int) {
일단 init에서 초기화되지 않은 속성들을 다 초기화 초기화해주고
그 외의 추가적으로 초기화된 속성들 중에 다시 초기화해주고 싶은 속성이 있을 때 convenience init을 사용하는 것으로 알고 있습니다.
이거를 사용하면  ` required init?(coder: NSCoder) {`를 오버라이딩 안해주어도 됩니다. 왜냐하면 self.init()에서 자동으로 상속되기 때문입니다.

이 방법말고 
```swift
init(totalSeconds: Int) {
        super.init(frame: CGRect(x: 0, y: 0, width: 300, height: 300))
        timerDuration = totalSeconds
        loadBackgroundProgressBar()
        loadForegroundProgressBar()
    }

    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
``` 도 가능합니다. 다만 이거는 왜인지는 모르겠는데 swiftFormat에서 계속 에러를 내네여 ..

2022-11-22 06:51 UTC, cozytk commented on SecretAgent/SecretAgent/Screen/Siren/View/Component/ProgressBar.swift
> +    convenience init(totalSeconds: Int) {
@KimDaeSeong8721  `@available(*, unavailable)`

2022-11-22 06:53 UTC, cozytk commented on SecretAgent/SecretAgent/Screen/Siren/View/Component/ProgressBar.swift
> +    convenience init(totalSeconds: Int) {
```
    init(totalSeconds: Int) {
        super.init(frame: CGRect(x: 0, y: 0, width: 300, height: 300))
        timerDuration = totalSeconds
        loadBackgroundProgressBar()
        loadForegroundProgressBar()
    }

    @available(*, unavailable)
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
```

swift format 저는 잘 됐어요!

2022-11-22 06:54 UTC, cozytk commented on SecretAgent/SecretAgent/Screen/Siren/View/Component/ProgressBar.swift
> +    convenience init(totalSeconds: Int) {
설명 감사합니다 :)

2022-11-23 02:20 UTC, JIW00NG approved these changes
승인 해드릴게요👍

2022-11-23 02:21 UTC, merged