[FEAT] Init UserNotificationManager
DeveloperAcademy-POSTECH/MacC-Team-SecretAgent pull request #16
Opened 2022-11-21 11:55 UTC by cozytk

## ⁴/₄ 관련 이슈

- close #3

## ⁴/₄ 작업내용

- UserNotificationManger를 구현하였습니다.

## ⁴/₄ PR 포인트

## ⁴/₄ 다음으로 진행될 작업
 - [ ] 유저의 알림에 따라 적절한 뷰로 네비게이팅
 - [ ] `AppDelegate` 와 `SceneDelegate` 에 알림 요청하고 보내는 코드 작성

2022-11-21 12:24 UTC, JIW00NG requested changes
뚝딱 뚝딱 코딩 잘하는 코지네요

2022-11-21 12:24 UTC, JIW00NG commented on SecretAgent/SecretAgent/Global/Service/UserNotificationService.swift
> +            center.requestAuthorization(options: options) { _, _ in }
궁금) 이런 경우 _, _ in 은 필수인 부분인가요?

2022-11-21 12:24 UTC, JIW00NG commented on SecretAgent/SecretAgent/Global/Service/UserNotificationService.swift
> +            }
p1

당신에게 아주 중요한 사실을 하나 들고왔습니다. 코지

알림을 설정할 때 UNNotificationRequest의 identifier가 동일하다면 이전 알림을 새 알림으로 대체한다고 나와 있어요. 그렇다면 이전에 설정했던 identifier와 동일하게 설정만 한다면? 지금과 같은 삭제하는 코드는 없어도 될 것 같습니다!

<img width="706" alt="Screenshot 2022-11-21 at 9 20 38 PM" src="https://user-images.githubusercontent.com/56468120/203054067-b744bc3f-5cd3-4c66-84d7-885c4368da47.png">

2022-11-21 12:24 UTC, JIW00NG commented on SecretAgent/SecretAgent/Global/Service/UserNotificationService.swift
> +            let uuidString = UUID().uuidString
setEvery에서의 uuid 는 저장할 필요가 없는 것인가요? 없다면 uuid로 설정할 필요가 있을까? 라는 의문이 생기네요...
그냥... 그렇다고요...

2022-11-21 12:36 UTC, cozytk commented on SecretAgent/SecretAgent/Global/Service/UserNotificationService.swift
> +            center.requestAuthorization(options: options) { _, _ in }
저도 궁금(

2022-11-21 12:39 UTC, cozytk commented on SecretAgent/SecretAgent/Global/Service/UserNotificationService.swift
> +            }
오 똑똑한 녀석이네요. 좋네요!! 그런데 지금 로직에서는 identifier를 매번 새롭게 생성해주어서 다른 identifier라서 활용하기 어려울 것 같아요. 캡쳐된 코드 부분은 이미 생성된 알림의 identifier를 지워주는 것이고, 새로 만들 알림은 또 identifier를 새로 생성해줍니다!

2022-11-21 12:42 UTC, cozytk commented on SecretAgent/SecretAgent/Global/Service/UserNotificationService.swift
> +            let uuidString = UUID().uuidString
Userdefaults에 uuid 를 저장하는 이유가  **pending 되어 있는 알림을 지워주기** 위해서였습니다! 매일 오는 알림은 지울일이 없는데, 저희 서비스에서 사이렌이 울린 후 15분 뒤 알림은 지워줄 필요가 있어서요!!

2022-11-21 14:04 UTC, cozytk commented
대면으로 개선점 이야기해서 반영해서 다시 올리겠습니다 :)

2022-11-22 09:39 UTC, Minkyeong-Ko approved these changes
코지 수고하셨습니다! 근데 PR 조금만 자세히 적어주세여..... 코지의 코드를 완벽히 이해하고 싶어요😁

2022-11-22 09:39 UTC, Minkyeong-Ko commented on SecretAgent/SecretAgent/Global/Service/UserNotificationService.swift
> +    func setEvery(at hour: Int, title: String, body: String, uuid: String) {
`setOnce`는 한 번만 실행되는 알림, `setEvery`는 주기적으로 실행되는 알림이라고 이해하면 될까요?

2022-11-22 09:39 UTC, Minkyeong-Ko commented on SecretAgent/SecretAgent/Global/Service/UserNotificationService.swift
> +            center.requestAuthorization(options: options) { _, _ in }
저도 궁금해요 알려주세요

2022-11-22 09:45 UTC, cozytk commented on SecretAgent/SecretAgent/Global/Service/UserNotificationService.swift
> +            center.requestAuthorization(options: options) { _, _ in }
@Minkyeong-Ko 안쓰니까 컴파일 에러 나긴 합니다!

2022-11-22 13:34 UTC, Minkyeong-Ko commented
> 

와!!! 너무 감사해요 코지👍🤩👃

2022-11-23 01:02 UTC, cozytk commented
<img width="465" alt="image" src="https://user-images.githubusercontent.com/59143479/203450690-50a062a3-4833-46b0-b991-05660c3be4ee.png">
Minkyeong-Ko는 잘못 눌렀어요 쏘리,,

2022-11-23 05:42 UTC, merged