[ADD] Core Data CRUD 기본 코드 작성
DeveloperAcademy-POSTECH/MacC-Team-SecretAgent pull request #17
Opened 2022-11-21 12:09 UTC by JIW00NG

## ⁴/₄ 관련 이슈

- close #15 

## ⁴/₄ 작업내용

1. 프로젝트 생성 시 Core Data 사용을 누르면 자동으로 생성되는 AppDelegate와 SceneDelegate의 코드를 제거하고 CoreDataManager를 따로 만들어 관리하도록 하였습니다.
2. Core Data에 저장할 Badge Entity를 추가하였고, Badge Entity에 저장될 Attributes인 number of todays coin (numberOfTodaysCoin)과 number of total coin (numberOfTotalCoin)을 추가하였습니다.
3. Core Data에 Data를 Fetch, Save하기 위해 CoreDataManager를 만들었습니다. 이때 CoreDataManager.swift 안에 다음과 같은 코드를 추가하여 하나의 static instance로 Core Data에 접근하도록 코드를 작성하였습니다.
4. 초기 뱃지의 총 갯수와 오늘의 뱃지 갯수를 저장하기 위해 initBadge()를 구현하여 각각 0으로 초기화하도록 하였습니다.
5. 사이렌이 울렸을 때 실패했을 경우를 대비하여 오늘의 뱃지 갯수를 1 씩 차감하는 함수인 decreaseTodaysBadge()를 구현하였습니다.
6. 알림을 받고 하루동안 얻은 뱃지를 정산하기 위해 오늘의 뱃지 갯수를 총 뱃지 갯수에 더하는 기능을 하는 updateTotalBadge()를 구현하였습니다.
7. 하루 정산이 완료되면 다음날부터 다시 하루 뱃지의 갯수가 5개부터 시작하기 때문에 numberOfTodaysCoin을 5로 초기화하는 resetTodaysBadge()를 추가하였습니다.
8. 현재 저장된 오늘의 뱃지 갯수와 총 뱃지 갯수를 가져오기 위한 fetchBadge()를 추가하였습니다.
9. Core Data에 저장된 뱃지의 갯수를 삭제하는 기능의 함수인 deleteBadge()를 언젠가는 사용되지 않을까 하는 마음으로 구현해놓았습니다.

## ⁴/₄ PR 포인트

* 이름이 적절한가!?
Entity의 이름은 Badge인데 안에 들어가는 Attribute들의 이름은 Coin으로 되어있습니다. CoinBadge가 기본이기 때문에 Coin으로 설정하였으나 결국 Badge 갯수가 아닌가 라는 생각이 자꾸 드네요. 의견이 있다면 말씀해주셨으면 좋겠습니다.

* 처음 AppDelegate에서 Core Data에 저장된 Badge가 없다면 init을 하는 코드를 실행합니다. 이 때, 다음 ViewController에서 fetch를 하면 정보가 없다고 나오는데 이 부분은 더 알아가면서 코드가 수정될 것 같습니다. 아시는 분이 계시다면 개인적으로 말해주세요. (공식적으로도 가능입니다.

## ⁴/₄ 다음으로 진행될 작업
 - [ ] ...

2022-11-22 04:58 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Global/Service/CoreDataManager.swift
> +
p2. 싱글톤 형태로 구현을 생각하신거라면

```suggestion
    static let shared = CoreDataManager()
    
    private init() { }
```
private init()을 추가해야 외부에서 새로운 인스턴스를 만드는 것을 방지할 수 있습니다..!

2022-11-22 05:12 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Global/Service/CoreDataManager.swift
> +                fatalError("Unresolved error \(nserror), \(nserror.userInfo)")
p5. 사소한 건데 카멜표기법 nsError로..!

2022-11-22 05:19 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Global/Service/CoreDataManager.swift
> +            } else {}
이부분이 이해가 잘 안되는데,,
현재코인의 개수가 0보다 작으면 현재뱃지에는 현재코인 개수 -1 , 즉 음수가 저장되는 거로 해석되는데 맞나영?.

2022-11-22 05:21 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Global/Service/CoreDataManager.swift
> +class CoreDataManager {
p5;
^.^
```suggestion
final class CoreDataManager {
```

2022-11-22 05:23 UTC, cozytk requested changes
고생하셨습니다!!! 대면으로도 리뷰 진행했습니다. 😁

2022-11-22 05:23 UTC, cozytk commented on SecretAgent/SecretAgent/Global/Service/CoreDataManager.swift
> +            if todaysCoin < 0 {
p1
`todaysCoin > 0` 아닌가요?!

2022-11-22 05:23 UTC, cozytk commented on SecretAgent/SecretAgent/Global/Service/CoreDataManager.swift
> +            if todaysCoin < 0 {
```suggestion
            if todaysCoin > 0 {
```

2022-11-22 05:23 UTC, cozytk commented on SecretAgent/SecretAgent/Global/Service/CoreDataManager.swift
> +    func fetchBadge() {
p4.

`fetchBadge()` 함수의 쓰임이 특별하게 있을까요? 뭔가 디버깅을 위해 필요한 함수 같아보이는데, 맞다면 `#if DEBUG` 로 전처리 구문에 감싸주는 것도 좋을 것 같아요

2022-11-22 05:25 UTC, KimDaeSeong8721 reviewed
깔끔한 코드 잘보았습니다. 코어데이터에 익숙치 않아서 제가 이해한 거는
코어데이터를 사용하기 위해서는 
컨테이너를 만들어주고, 컨테이너의 viewContext를 이용하여 인스턴스를 가져오고 
이 인스턴스를 변경하고 저장하고싶으면 saveContext()를 호출하는 과정으로 이해하면 될까여?

2022-11-22 05:35 UTC, cozytk commented
Swiftformat 관련된 빌드 에러가 있어서 fomrat 돌리고 다시 올렸습니다!

2022-11-22 09:24 UTC, Minkyeong-Ko commented on SecretAgent/SecretAgent/Global/Service/CoreDataManager.swift
> +
우와.. 처음 알았습니다!!

2022-11-22 09:25 UTC, Minkyeong-Ko commented on SecretAgent/SecretAgent/Global/Service/CoreDataManager.swift
> +            } else {}
코지가 적어주신 게 맞는 것 같아요 if 문이 반대가 되어야 할 것 같습니다!

2022-11-22 09:32 UTC, Minkyeong-Ko approved these changes
Core Data 마스터 우기 수고하셨습니다 💪

2022-11-22 09:32 UTC, Minkyeong-Ko commented on SecretAgent/SecretAgent/Global/Service/CoreDataManager.swift
> +    func fetchBadge() {
가짜 우기인데요, `fetchBadge` 함수는 뱃지 데이터를 CoreData 에서 가져오는 함수입니다. 현재는 단순히 값을 가져와서 print만 해 주고 있지만, 추후 다른 뷰컨트롤러들이나 뱃지 수 정보가 필요한 곳에서 사용될 예정입니다!

2022-11-22 09:32 UTC, Minkyeong-Ko commented on SecretAgent/SecretAgent/Global/Service/CoreDataManager.swift
> +            newBadge.numberOfTotalCoin = 0
p3.
지금 보니 `numberOfTotalCoins` 와 `numberOfTotalCoins` 가 되면 좋을 것 같네요! 복수형으로..ㅎㅎ

그리고 오늘 획득할 코인이랑 전체 코인 attribute 이름이 비슷하게 생겨서 좀 헷갈리는 것 같아요. 
오늘 획득할 코인 attribute 이름을 `coinsLeftForToday` 이런 걸로 바꾸는 건 어떨까요?!

2022-11-23 08:12 UTC, JIW00NG commented on SecretAgent/SecretAgent/Global/Service/CoreDataManager.swift
> +            newBadge.numberOfTotalCoin = 0
저도 네이밍이 마음에 들지 않았는데 좋은 의견 감사합니다!
numberOfTotalCoin -> numberOfTotalCoins
numberOfTodaysCoin -> coinsLeftForToday로 수정하였습니다. ㅎㅎ

2022-11-23 08:12 UTC, JIW00NG commented on SecretAgent/SecretAgent/Global/Service/CoreDataManager.swift
> +                fatalError("Unresolved error \(nserror), \(nserror.userInfo)")
별로 중요한 에러가 아니기 때문에 그냥 error를 출력하도록 수정하였습니다.

2022-11-23 08:12 UTC, JIW00NG commented on SecretAgent/SecretAgent/Global/Service/CoreDataManager.swift
> +            } else {}
그러네요 ... ㅎㅎ😅

2022-11-23 08:12 UTC, JIW00NG commented on SecretAgent/SecretAgent/Global/Service/CoreDataManager.swift
> +            if todaysCoin < 0 {
맞아요.. ㅎㅎ😅

2022-11-23 08:13 UTC, JIW00NG commented on SecretAgent/SecretAgent/Global/Service/CoreDataManager.swift
> +    func fetchBadge() {
fetchBadge()는 처음에 데이터를 가져오는 함수를 테스트용도로 만들어본 것이며 이름을 바꾸고 다르게 수정하였습니다.

2022-11-23 08:17 UTC, JIW00NG commented
> 깔끔한 코드 잘보았습니다. 코어데이터에 익숙치 않아서 제가 이해한 거는
> 코어데이터를 사용하기 위해서는
> 컨테이너를 만들어주고, 컨테이너의 viewContext를 이용하여 인스턴스를 가져오고
> 이 인스턴스를 변경하고 저장하고싶으면 saveContext()를 호출하는 과정으로 이해하면 될까여?

맞습니다. NSManagedObjectModel, NSManagedObjectContext, NSPersistentStoreCoordinator를 갖는 NSPersistentContainer 객체를 만들고 데이터 조작을 한 뒤 마지막으로 NSManagedObjectContext의 save()를 해주어야 합니다. Core Data는 save()를 하지 않으면 앱이 종료됬을 경우 데이터가 저장되지 않기 때문에 마지막에 context.save()를 해야 합니다.

2022-11-23 08:18 UTC, JIW00NG commented
코지와 대면으로 CoreDataManager는 이름 그대로 CoreData와 관련된 일만을 하게 일반적인 class로 수정하였으며, CoreDataManager를 상속받는 BadgeManager를 추가하여 뱃지 관련 데이터 처리를 BadgeManager에서 처리하도록 수정하였습니다.

2022-11-23 08:31 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Global/Support/AppDelegate.swift
> +        BadgeManger.shared.initBadge()
여기서 초기화하셨군요. 👍

2022-11-23 16:53 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Model/BadgeManager.swift
> +final class BadgeManger: CoreDataManager {
BadgeManaer의 위치를 Model에 둔 이유가 있나용?! 궁금합니다

2022-11-23 16:57 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Model/BadgeManager.swift
> +final class BadgeManger: CoreDataManager {
> 코지와 대면으로 CoreDataManager는 이름 그대로 CoreData와 관련된 일만을 하게 일반적인 class로 수정하였으며, CoreDataManager를 상속받는 BadgeManager를 추가하여 뱃지 관련 데이터 처리를 BadgeManager에서 처리하도록 수정하였습니다.
 아 여기 있군요.. 감사합니다

2022-11-23 16:58 UTC, KimDaeSeong8721 approved these changes
고생하셨습니다. 우기!! 상속개념을 잘 활용하시는게 너무 멋있네여 :) 배워갑니다 😊

2022-11-24 00:11 UTC, Minkyeong-Ko approved these changes
공통된 기능만 CoreDataManager로 빼고 BadgeManager를 따로 두는 구조 너무 좋네요! 수고하셨습니다👍 이전 코드도 좋았는데 더 발전된 모습 너무 좋습니다

2022-11-25 03:46 UTC, cozytk approved these changes
대면으로 재사용되는 fetchBadge 코드를 따로 함수로 만들어 더 나은 추상화를 제공하기 위해 이야기 하였습니다!

2022-11-26 02:47 UTC, JIW00NG commented
Cozy와 대면으로 대화하여 fetchBadge()를 따로 만들어 중복되는 다음과 같은 코드를 제거하였습니다.

```swift
let request = Badge.fetchRequest()
```

또한 BadgeManager의 위치를 CoreDataManger와 동일한 /Global/Service로 이동하였습니다.

2022-11-26 02:57 UTC, merged