[FEAT] 사이렌 구현
DeveloperAcademy-POSTECH/MacC-Team-SecretAgent pull request #18
Opened 2022-11-22 07:46 UTC by Minkyeong-Ko

## ⁴/₄ 관련 이슈

- close #14 

## ⁴/₄ 작업내용

- 밀러가 이미 만드신 `SirenViewController`가 있지만 아직 로직이 정확히 나오지 않아서, `TestSirenViewController` 를 만들어서 사이렌이 울리는 것을 구현했습니다.
- 오디오를 재생만 하고 멈출 필요도 없고 길이가 짧아서 자동으로 끝내게 두면 될 것 같아서 우선 굉장히 간단하게.. 작성해 보았습니다.
- 파일 이름을 문자열 그대로 사용하고 싶지 않아(실수나 오타의 가능성 때문에) `SoundLiteral` 파일을 추가했습니다. 추후 다른 효과음이 앱에 들어간다면 여기 정리해도 좋을 것 같습니다.

## ⁴/₄ PR 포인트

- `SoundLiteral` 과 `MusicExtension` enum이 같은 파일에 존재해도 괜찮을지 고민입니다.
- @JIW00NG 태스크가 늘어나야 할 것 같아서 스크럼 회의를 한번 더 하면 좋을 것 같은데 어떠신가요..?!

## ⁴/₄ 다음으로 진행될 작업
 - [ ] 하이파이가 결정되면..

2022-11-22 12:16 UTC, cozytk requested changes
> SoundLiteral 과 MusicExtension enum이 같은 파일에 존재해도 괜찮을지 고민입니다.

저는 괜찮을 것 같습니다! `MusicExtension` 을 사용하는 경우가 `SoundLiteral` 밖에 없다고 생각해서요!

> 사이렌 소리가 끝나면 타이머 화면으로 이동하면 좋을 것 같아 audioPlayerDidFinishPlaying 에 TODO를 추가하였습니다. 이 플로우가 괜찮을까요?

저는 괜찮아 보입니다!

2022-11-22 12:16 UTC, cozytk commented on SecretAgent/SecretAgent/Screen/Siren/TestSirenViewController.swift
> +}
p1.

이 부분이 세팅해주는 부분과 실행하는 부분으로 나뉘면 좋을 것 같아요. 제가 테스트 해보았을 때, 처음 실행할 때는 딜레이가 좀 있어서 `play` 하는 시점보다 앞서 `prepareToPlay` 함수가 호출되면 좋을 것 같아요!

제안드리고 싶은 형태는 아래와 같습니다!

```swift
override func viewDidLoad() {
    super.viewDidLoad()
    setSiren()
}
```

```swift
func setSiren() {
    guard let path = Bundle.main.path(forResource: SoundLiteral.siren.fileName(), ofType: nil) else { return }
    let url = URL(fileURLWithPath: path)

    do {
        sirenPlayer = try AVAudioPlayer(contentsOf: url)
        sirenPlayer?.prepareToPlay()
        sirenPlayer?.delegate = self
    } catch {
        print(error)
    }
}

@objc func playSiren() {
    sirenPlayer?.play()
}
```

2022-11-22 12:16 UTC, cozytk commented on SecretAgent/SecretAgent/Screen/Siren/TestSirenViewController.swift
> +    private var sirenPlayer: AVAudioPlayer?
p4.

```suggestion
    private var sirenPlayer: AVAudioPlayer!
```

아래에 sirenPlayer를 호출하기 전에 할당될 것이 보장되니 다음과 같이 선언하고 밑에 옵셔널로 처리하지 않는게 더 좋다고 생각해요 :) 꼭 필요하지 않으면 옵셔널로 만들 필요가 없다고 생각해서요! 다니의 의견이 궁금합니다!

2022-11-22 12:19 UTC, cozytk commented on SecretAgent/SecretAgent/Screen/Siren/TestSirenViewController.swift
> +        guard let path = Bundle.main.path(forResource: SoundLiteral.siren.fileName(), ofType: nil) else { return }
```swift
guard let path = Bundle.main.path(forResource: SoundLiteral.siren, ofType: MusicExtension.mp3) else { return }
```

리터럴을 문자열 그래도 쓰고싶지 않으면 이렇게 할 수도 있겠네요 ㅎㅎㅎ MusicExtension을 internal로 유지한다면!! 사소하게 넘어가주세요

2022-11-22 12:20 UTC, cozytk commented on SecretAgent/SecretAgent/Screen/Siren/TestSirenViewController.swift
> +}
딜레이가 없는 걸 확실히 보장하고 싶다면 아예 `SceneDelegate` 같은 곳에서 `AVAudioPlayer` 객체를 만드는 것도 좋을 거 같은데 어떻게 생각하시나요?!

2022-11-22 13:36 UTC, Minkyeong-Ko commented on SecretAgent/SecretAgent/Screen/Siren/TestSirenViewController.swift
> +        guard let path = Bundle.main.path(forResource: SoundLiteral.siren.fileName(), ofType: nil) else { return }
오 좋아요!! 꼼꼼코지 감사합니다 👍

2022-11-22 13:39 UTC, Minkyeong-Ko commented on SecretAgent/SecretAgent/Screen/Siren/TestSirenViewController.swift
> +}
안 그래도 저 부분을 분리하고 싶었는데 미처 못했었어요..😂 
코지 제안 너무 감사합니다! 정말 좋은 것 같아요 바로 반영하겠습니다ㅎㅎ

2022-11-22 13:41 UTC, Minkyeong-Ko commented on SecretAgent/SecretAgent/Screen/Siren/TestSirenViewController.swift
> +}
> 딜레이가 없는 걸 확실히 보장하고 싶다면 아예 `SceneDelegate` 같은 곳에서 `AVAudioPlayer` 객체를 만드는 것도 좋을 거 같은데 어떻게 생각하시나요?!

요것도 분리한 다음 시도해 보겠습니다! 크 덕분에 시야가 넓어집니다..👍

2022-11-22 14:10 UTC, Minkyeong-Ko commented on SecretAgent/SecretAgent/Screen/Siren/TestSirenViewController.swift
> +        guard let path = Bundle.main.path(forResource: SoundLiteral.siren.fileName(), ofType: nil) else { return }
<img width="638" alt="스크린샷 2022-11-22 오후 11 09 45" src="https://user-images.githubusercontent.com/78426896/203335045-8ecb872d-12c3-4165-b2fb-f17736446ee4.png">

익스텐션을 nil 말고 직접 지정하는 게 성능에도 도움이 되겠네요..! 덕분에 많이 알아갑니다ㅎㅎ

2022-11-23 00:47 UTC, JIW00NG approved these changes
척척 해내는 다뉘

2022-11-23 00:47 UTC, JIW00NG commented on SecretAgent/SecretAgent/Global/Literal/SoundLiteral.swift
> +    }
p5
궁금한 부분인데 보통 swift에서 enum의 rawValue를 가져오는 함수의 이름을 callAsFunction으로 짓나요?

2022-11-23 01:01 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Global/Literal/SoundLiteral.swift
> +    }
p3;
궁금한 점이 있습니다!. enum의 값의 rawValue는 직접 가져올 수 있는데 함수를 만들어준 이유가 있나영??
`SoundLiteral.siren.rawValue`

2022-11-23 01:04 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Screen/Siren/TestSirenViewController.swift
> +        guard let path = Bundle.main.path(forResource: SoundLiteral.siren(), ofType: MusicExtension.mp3()) else { return }
p4;
callAsFunction()을 정의함에 따라 저런 방식으로 사용할 수 있는건가여?

2022-11-23 01:07 UTC, Minkyeong-Ko commented on SecretAgent/SecretAgent/Global/Literal/SoundLiteral.swift
> +    }
참고 블로그: https://zeddios.tistory.com/985
Swift 5.2에서 새로 추가된 문법인데, 정적으로 호출 가능한 값(`statically callable values`) 이라고 해서 타입의 값을 함수 형식으로 바로 호출할 수 있는 메소드라고 합니다.
그래서 SoundLiteral.siren() 이렇게 바로 사용할 수 있게 되어서 편리한 것 같아서 사용하였습니다!

2022-11-23 01:08 UTC, Minkyeong-Ko commented on SecretAgent/SecretAgent/Global/Literal/SoundLiteral.swift
> +    }
그렇긴 하지만 SoundLiteral.siren() 이게 좀 더 편리한 것 같아서 사용하였습니다..! 별 다른 이유는 없어요ㅠㅠ

2022-11-23 01:08 UTC, Minkyeong-Ko commented on SecretAgent/SecretAgent/Screen/Siren/TestSirenViewController.swift
> +        guard let path = Bundle.main.path(forResource: SoundLiteral.siren(), ofType: MusicExtension.mp3()) else { return }
네 맞습니다! https://github.com/DeveloperAcademy-POSTECH/MacC-Team-SecretAgent/pull/18#discussion_r1029947364

2022-11-23 01:17 UTC, KimDaeSeong8721 approved these changes
고생하셨습니다!! 다니 ㅎㅎ 👏

2022-11-23 02:16 UTC, merged