[ADD]: 이미지 에셋 추가 #27
DeveloperAcademy-POSTECH/MacC-Team-SecretAgent pull request #28
Opened 2022-11-25 09:15 UTC by cozytk

## ⁴/₄ 관련 이슈

- close #27 

## ⁴/₄ 작업내용

<img width="1504" alt="스크린샷 2022-11-25 오후 4 50 09" src="https://user-images.githubusercontent.com/59143479/203943768-1f501148-f001-47d9-bc0d-b619668f533d.png">

- 공통적으로 사용하는 에셋들을 추가하였습니다.
- 사이즈가 기기마다 혹은 뷰마다 동적으로 변한다고 판단되는 것들은 `svg` 로 모든 뷰와 기기에서 고정적인 크기를 가질 것 같은 이미지는  `png`로 가져왔습니다.
  - ex ) woongwoong 66x66

## ⁴/₄ PR 포인트

- 네이밍이 적절한지
- svg 파일로 가져와서 single scale을 적용한 것이 괜찮은지

2022-11-26 08:33 UTC, Minkyeong-Ko approved these changes
수고하셨습니다👍

2022-11-26 08:33 UTC, Minkyeong-Ko commented on SecretAgent/SecretAgent/Global/Literal/ImageLiteral.swift
> -    static var sampleRoom: UIImage { .load(named: "SampleRoom") }
예시 삭제 감사합니다👍

2022-11-26 08:33 UTC, Minkyeong-Ko commented on SecretAgent/SecretAgent/Global/Literal/ImageLiteral.swift
> +    static var deactivateStar: UIImage { .load(named: "star.deactivate") }
p3. 
사실 크게 문제는 없지만, inactive가 active의 반대 뜻과 좀 더 가까운 것 같아 deactive 보다는 inactive를 사용하는 것이 어떨까요?

2022-11-26 08:33 UTC, Minkyeong-Ko commented on SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/coin.activate.imageset/Contents.json
> +      "filename" : "coin.activate.svg",
(단순 궁금증 입니다)
png와 svg를 따로 두면 좋은 점이 무엇인가요?

2022-11-26 09:49 UTC, cozytk commented on SecretAgent/SecretAgent/Global/Literal/ImageLiteral.swift
> +    static var deactivateStar: UIImage { .load(named: "star.deactivate") }
좋은 의견 감사합니다 :) 반영하겠습니다.

2022-11-26 09:49 UTC, cozytk commented on SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/coin.activate.imageset/Contents.json
> +      "filename" : "coin.activate.svg",
따로 둔다는 의미를 제가 제대로 이해했는지 모르겠지만,
저는 디바이스 혹은 화면에 따라 다른 프레임크기의 에셋이 필요할 것 같으면 svg,
고정된 크기의 에셋을 사용할 것 같으면 png로 가져왔습니다!

2022-11-26 09:49 UTC, cozytk commented on SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/coin.activate.imageset/Contents.json
> +      "filename" : "coin.activate.svg",
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-SecretAgent/pull/28/commits/75567f17a4a45d8bf03a3aa05af093709d882585

2022-11-26 09:50 UTC, cozytk commented on SecretAgent/SecretAgent/Global/Literal/ImageLiteral.swift
> +    static var deactivateStar: UIImage { .load(named: "star.deactivate") }
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-SecretAgent/pull/28/commits/75567f17a4a45d8bf03a3aa05af093709d882585

2022-11-26 13:11 UTC, Minkyeong-Ko commented on SecretAgent/SecretAgent/Global/Resource/Assets.xcassets/coin.activate.imageset/Contents.json
> +      "filename" : "coin.activate.svg",
png도 크기 조절이 가능할텐데 svg를 쓰는 이유가 궁금했는데, 검색을 통해 해결했습니다..☺️
svg는 벡터 이미지라 픽셀이 깨지지 않는 군요!

2022-11-26 23:01 UTC, JIW00NG requested changes
요원들도 다 넣어주세요. 요원들이 슬퍼해요

2022-11-26 23:03 UTC, JIW00NG approved these changes
요원 이미지의 경우 제가 넣도록 하겠습니다!
감사해요 코지! 그리고 svg, pdf를 언제 어떻게 사용할지 몰랐는데 덕분에 그런 이유가 있다는 것을 알게 되었습니다.

2022-11-28 00:52 UTC, KimDaeSeong8721 approved these changes
귀찮은 작업일텐데 감사합니다. svg는 벡터로 구성되어 있어서 single Scale하는 거 괜찮다고 생각합니다:)

2022-11-28 06:15 UTC, merged