[FEAT] 메인 탭 뷰 인터페이스 구현
DeveloperAcademy-POSTECH/MacC-Team-SecretAgent pull request #32
Opened 2022-11-26 11:35 UTC by cozytk

## ⁴/₄ 관련 이슈

- close #26

## ⁴/₄ 작업내용

- 공통되는 에셋, 폰트, 이미지 일부를 추가하였습니다.
- MainTabBar를 구성하였습니다.
  - 탭바를 선택됨 & 선택되지 않음에 따라 탭바 이미지 변경
- Navigation Bar를 구성하였습니다.
  - 보드 뷰에서는 초록색 배경
  - 스토리 뷰에서는 요원증 사진
  - 폰트는 아직 적용하지 않았습니다.

## ⁴/₄ PR 포인트

- 전체적인 네이밍과 가독성에 대한 조언 적극 반영하겠습니다!!

## ⁴/₄ 다음으로 진행될 작업
 - [ ] 요원증이랑 오늘의 코인 버튼 만들기

2022-11-26 23:47 UTC, JIW00NG approved these changes
메인 탭 뷰 구현 잘 봤습니다!
고민하던 상황은 아래 같이 적어놓았습니다만.. 고민의 답은 나오지 않았습니다 ㅎㅎㅎ..

> setNavigationControllers() 안에서 configureNavigationController()로 설정하고 있는 것을 확인하였습니다. setNavigationControllers -> configureNavigationControllers 는 이해하는데 어려움이 있을지 궁금합니다.
그리고 두 함수의 네이밍을 고민해보았지만... 마땅한 답이 떠오르지 않네요.

>또한 configureNavigationController의 경우 UINavigationController를 return 하고 있는데 그러면 configure가 아닌 다른 이름을 사용해야할 것으로 보입니다. 히지만 이 또한 적절한 네이밍이 생각이 나질 않네요...

2022-11-26 23:47 UTC, JIW00NG commented on SecretAgent/SecretAgent/Global/Extension/Preview+Extension.swift
> +//  Created by 리아 on 2022/10/16.
여기 다른분이 껴있군요...😅

2022-11-26 23:47 UTC, JIW00NG commented on SecretAgent/SecretAgent/Screen/Main/MainTabViewController.swift
> +        let boardNavigation = configureNavigationController(
p3
이름에 Tab 넣는 건 어떻게 생각하시나요?

2022-11-26 23:47 UTC, JIW00NG commented on SecretAgent/SecretAgent/Screen/Main/MainTabViewController.swift
> +        let horizontalStackView = UIStackView(arrangedSubviews: [todayBadgeButton])
p4
hStackView도 괜찮을 것 같아요.
지난번에 얘기했던 부분들이 생각나서 저도 hStack처럼 네이밍을 하고 있습니다.

2022-11-26 23:47 UTC, JIW00NG commented on SecretAgent/SecretAgent/Screen/Main/MainTabViewController.swift
> +private final class TodayBadge: UIStackView {
p3
TodayBadge View의 정의는 Screen/Main/View folder 위치로 따로 빼놓고 다른 파일로 관리하고 사용하는 것도 괜찮을 것이라고 생각해요.
저는 그렇게 생성한 뷰들도 다른 파일로 관리하는 편입니다. 개인적인 코드 스타일이긴 하지만 이런 부분도 다같이 맞춰가는 것도 좋을 것 같아요

2022-11-27 03:52 UTC, cozytk commented on SecretAgent/SecretAgent/Global/Extension/Preview+Extension.swift
> +//  Created by 리아 on 2022/10/16.
다른 레포에서 가져와서 그대로 두었습니다!

2022-11-27 03:53 UTC, cozytk commented on SecretAgent/SecretAgent/Screen/Main/MainTabViewController.swift
> +        let boardNavigation = configureNavigationController(
`boardTab` 과 같은 방식인가요?? 좋아보여요!!

2022-11-27 03:54 UTC, cozytk commented on SecretAgent/SecretAgent/Screen/Main/MainTabViewController.swift
> +        let horizontalStackView = UIStackView(arrangedSubviews: [todayBadgeButton])
그랬었군요? 저도 hStack 파에요

2022-11-27 03:56 UTC, cozytk commented on SecretAgent/SecretAgent/Screen/Main/MainTabViewController.swift
> +private final class TodayBadge: UIStackView {
`TodayBadge` 가 재사용되지 않을 클래스라서 다른 파일에 빼두어 `private` 에서 `internal` 로 접근 제어를 낮추는 것이 꺼려졌었어요!
파일을 나누었을 때 장점도 분명하고 팀에서 두루 사용하는 스타일이니 분리하여 놓겠습니다!

2022-11-27 04:16 UTC, JIW00NG commented on SecretAgent/SecretAgent/Global/Extension/Preview+Extension.swift
> +//  Created by 리아 on 2022/10/16.
아하 출처를 남기신거였군요! 알겠습니다!

2022-11-27 04:16 UTC, JIW00NG commented on SecretAgent/SecretAgent/Screen/Main/MainTabViewController.swift
> +        let horizontalStackView = UIStackView(arrangedSubviews: [todayBadgeButton])
그럼 이제 다음 의문
hstack 일까요 hStack일까요?

2022-11-27 04:17 UTC, JIW00NG commented on SecretAgent/SecretAgent/Screen/Main/MainTabViewController.swift
> +private final class TodayBadge: UIStackView {
감사합니다 ㅎㅎ

2022-11-27 04:40 UTC, cozytk commented on SecretAgent/SecretAgent/Screen/Main/MainTabViewController.swift
> +        let horizontalStackView = UIStackView(arrangedSubviews: [todayBadgeButton])
hStack 추진해봅니다

2022-11-27 05:14 UTC, Minkyeong-Ko approved these changes
수고하셨습니다! 너무나 신기한 코드들이네요 탭 뷰 구현에 대해 많이 배웠습니다👍

2022-11-27 05:19 UTC, cozytk commented on SecretAgent/SecretAgent/Global/Extension/Color+Extension.swift
> +    // MARK: - yo colors
`Figma` 에서 사용하는 색상들을 `yo` 라는 접두사를 사용해서 가져왔는데, 더 이해가 잘 되게 고민해보겠습니다.

2022-11-27 05:21 UTC, cozytk commented on SecretAgent/SecretAgent/Global/Extension/Preview+Extension.swift
> +//  Created by 리아 on 2022/10/16.
굳이 비슷한 내용을 새로 만들지 않고 참고한 코드 레퍼런스를 남겨놓으려는 의도가 있었는데, 말씀 들어보니 저희에 맞게 수정한다음에 레퍼런스를 따로 주석으로 남아두는 게 더 낫겠네요!

2022-11-27 05:22 UTC, cozytk commented on SecretAgent/SecretAgent/Screen/Main/MainTabViewController.swift
> +        let todayBadgeButton = TodayBadge()
반영하겠습니다!

2022-11-28 00:56 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Global/Extension/Color+Extension.swift
> +    // MARK: - yo colors
네이밍관련해서 디자이너분들과 논의를 해보는 것도 좋을거같아요 :)

2022-11-28 01:02 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Screen/Main/MainTabViewController.swift
> +        let todayBadgeButton = TodayBadge()
p3;
다니 말씀처럼 View임을 명시적으로 보여주기 위해 TodayBadgeView와 같은 네이밍이 적절해보이고 파일을 따로 만드는 게 좋을 거 같아요 :)

2022-11-28 01:07 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Screen/Main/MainTabViewController.swift
> +private final class TodayBadge: UIStackView {
공통적으로 사용하는 컴포넌트들은 Global/UIComponent에 파일을 생성해서 관리하고 특정뷰에서만 사용되는 컴포터는트들은 Screen/Main(예시)/View/Component에서 파일을 생성해서 관리하면 좋을 거같습니다. 감사합니다

2022-11-28 01:09 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Screen/Main/MainTabViewController.swift
> +class MainTabViewController: UITabBarController {
p2;
가독성을 위해서 마크 주석 부탁드려요 🙌
그리고 render()함수 만들어서 그 안에 레이아웃관련된 코드들을 넣어두면 추후 관리하기 편할 거 같아요 🤘

2022-11-28 02:36 UTC, KimDaeSeong8721 requested changes
고생 많으셨어요!! 코지

2022-11-28 04:00 UTC, cozytk commented on SecretAgent/SecretAgent/Screen/Main/MainTabViewController.swift
> +class MainTabViewController: UITabBarController {
확인했습니다! 반영하겠습니다.

2022-11-29 07:49 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Screen/Main/BaseNavigationController.swift
> +    private var navigationBarFooter: UIView!
처음에 이뷰들이 무엇을 뜻하는지 이해를 못해서 여러 시도를 해보았는데요.
NavigationBar의 사이즈 조절 불가로 인해 발생하는 이슈들을 해결하기 위해 NavigationBar위쪽과 NavigationBar 아래쪽에 색을 채운 뷰를 추가한 걸로 이해했습니다. 아주 멋있어요..! 
그러나 동시에 한 가지 생각이 들었습니다. NavigationBar가 우리를 괴롭힌다면.. NavigationBar를 숨겨버리고CustomNavigationBar:UIView 를 만들면 되지 않을까?
혹시 후자도 고려를 하셨던건지 궁금해요! 고려를 하셨다면 전자로 만든 이유가 있을까요?

2022-11-29 07:50 UTC, KimDaeSeong8721 commented on SecretAgent/SecretAgent/Screen/Main/View/Component/AgentCard.swift
> +            addArrangedSubview(subView)
오호 신박하네요. 매번 addArrangedSubview하기 귀찮았는데 forEach를 까먹고 있었네요. 감사합니다 코지!!

2022-11-29 07:56 UTC, KimDaeSeong8721 approved these changes
코지 네비게이션바와의 싸움에서 고생많으셨습니다!! 어프루브드립니당

2022-11-29 13:52 UTC, merged